SELECT ccu.COLUMN_NAME
FROM
	INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS tc
	JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE AS ccu
ON ccu.CONSTRAINT_NAME = tc.CONSTRAINT_NAME
WHERE ccu.TABLE_NAME = ('file') AND tc.CONSTRAINT_TYPE='PRIMARY KEY'