select ccu.COLUMN_NAME
FROM
	INFORMATION_SCHEMA.TABLE_CONSTRAINTS as tc
	JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE as ccu
ON ccu.CONSTRAINT_NAME = tc.CONSTRAINT_NAME
WHERE ccu.TABLE_NAME = 'File' AND tc.CONSTRAINT_TYPE='PRIMARY KEY'